---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: library
  REPOSITORY_TYPE: python

includes:
  common: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-common.yml
  python: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-python.yml
  fix: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-fix.yml
  lint: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-lint.yml
  software: ./.common/taskfiles-{{.REPOSITORY_SUBTYPE}}/Taskfile-{{OS}}.yml
